# 流水线分为测试阶段和构建阶段
stages:
  - test
  - build

# 测试作业
test:
  stage: test
  image: golang:1.15
  tags:
    - my-tag
  # 执行脚本前的工作，设置 goproxy 加快依赖下载速度
  before_script:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
  # 执行代码检查和单元测试
  script:
    - go vet ./...
    - go test -v -race ./...

# 编译阶段
build:
  stage: build
  image: golang:1.15
  tags:
    - my-tag
  before_script:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
  script:
    - go build app ./content/main.go